### ISSUE TITLE
tests fail in org.openscience.cdk.config.AtomTypeFactoryTest

### ISSUE THREAD

**Issue by uli-f** [cdk/cdk#882] opened 2022-08-26 01:33 UTC
Five tests fail for me in `AtomTypeFactoryTest`:

```
testXMLValidityMM2
testXMLValidityMMFF94
testXMLValidityMol2
testXMLValidityPDB
testXMLValidityStructGen

```
Here is the stacktrace for `testXMLValidityMM2`, the stack traces for the other four test methods look very comparable.

```
java.lang.AssertionError: MM2 is not valid on line 10: cvc-elt.1.a: Cannot find the declaration of element 'atomTypeList'.

	at org.junit.Assert.fail(Assert.java:89)
	at org.openscience.cdk.config.AtomTypeFactoryTest$SAXValidityErrorHandler.error(AtomTypeFactoryTest.java:390)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:138)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2133)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:830)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3079)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:247)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:342)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
	at org.openscience.cdk.config.AtomTypeFactoryTest.assertValidCML(AtomTypeFactoryTest.java:341)
	at org.openscience.cdk.config.AtomTypeFactoryTest.testXMLValidityMM2(AtomTypeFactoryTest.java:301)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```
Any help is much appreciated.

**Comment by uli-f** [comment] 2022-08-26 01:59
A comparable test failure also pops up in `org.openscience.cdk.config.XMLIsotopeFactoryTest.testXMLValidityHybrid`.

**Comment by johnmay** [comment] 2022-08-26 06:46
jvm version?

**Comment by uli-f** [comment] 2022-08-26 06:49
> jvm version?

I am on 17.0.3

**Comment by johnmay** [comment] 2022-08-26 07:17
Oracle, openjdk, azul?

**Comment by uli-f** [comment] 2022-08-26 07:23
Apologies, my bad, that was very unspecific.

I am all Adoptium:
```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)
```

**Comment by johnmay** [comment] 2022-08-26 20:13
Are you running from the IDE or via the maven command line?

**Comment by johnmay** [comment] 2022-08-26 20:15
Could you try modify the XML file: mm2_atomtypes.xml

```
<atomTypeList xmlns="http://www.xml-cml.org/schema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.xml-cml.org/schema ../../io/cml/data/cml25b1.xsd"

  xmlns:cvs="https://www.cvshome.org/"
  xmlns:cdk="http://cdk.sf.net/dict/cdk/"

  id="mm2" title="MM2 AtomTypes">

```

1) remove extra blank lines

```
<atomTypeList xmlns="http://www.xml-cml.org/schema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://www.xml-cml.org/schema ../../io/cml/data/cml25b1.xsd"
  xmlns:cvs="https://www.cvshome.org/"
  xmlns:cdk="http://cdk.sf.net/dict/cdk/"
  id="mm2" title="MM2 AtomTypes">
```

2) if that does nothing try replacing with spaces:

```
<atomTypeList xmlns="http://www.xml-cml.org/schema"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xml-cml.org/schema ../../io/cml/data/cml25b1.xsd" xmlns:cvs="https://www.cvshome.org/" xmlns:cdk="http://cdk.sf.net/dict/cdk/" id="mm2" title="MM2 AtomTypes">

```

This is really odd if either those resolves the issue since whitespace like this should be fine in XML. Clearly you can see the GitHub actions are running find on JDK 8 - 17.

**Comment by uli-f** [comment] 2022-08-29 01:45
> Are you running from the IDE or via the maven command line?

I run the tests from the IDE (Intellij).

**Comment by uli-f** [comment] 2022-08-29 03:07
Unfort, both

> 1. remove extra blank lines

and

> 2. if that does nothing try replacing with spaces:

did not solve the issue.

However, looking at `mm2_atomtypes.xml`  Intellij points out issues at line 3 and marks them in red:

1. `xsi:schemaLocation="http://www.xml-cml.org/schema ../../io/cml/data/cml25b1.xsd"` -> cannot resolve file cml25b1.xsd; it seems a bit fishy to me to put a relative path here, I don't think that can get resolved across jars even if it would be correct.. ❓ 
2. `xmlns:cvs="https://www.cvshome.org/"` -> URI not registered; leads to a website for hiring contractors 🤷🏼 
3. `xmlns:cdk="http://cdk.sf.net/dict/cdk/"` -> URI not registered; I actually get a 404 when putting a request to that URI

Also, the URI in line 2 does not lead to an existing URL:

`<?xml-stylesheet type="text/xsl" href="http://cdk.svn.sourceforge.net/viewvc/*checkout*/cdk/trunk/cdk/src/org/openscience/cdk/config/data/html.xsl?content-type=text%2Fxml"?>`

I dimly remember that - when using XML files with our own schema years ago - we added custom resolvers to the XML library so that the URIs to the schema got resolved against a file in the file system.

And to the best of my knowledge different XML libraries have different levels of validation in place. So where one library might be fine (or just logs an error), another might throw an exception.

It feels like the whole XML parsing world of Java is a bit similar to the realm of logging libraries 😬

**Comment by uli-f** [comment] 2022-08-29 03:48
Spend a bit more time on this and found out the following:

As already suspected the issue here is locating the file `../../io/cml/data/cml25b1.xsd` in line 3 of `mm2_atomtypes.xml`:
`xsi:schemaLocation="http://www.xml-cml.org/schema ../../io/cml/data/cml25b1.xsd`

When I change this to
`xsi:schemaLocation="http://www.xml-cml.org/schema http://www.xml-cml.org/schema/schema24/schema.xsd`
the test passes.

The reason for this is described in this post at stackoverflow: https://stackoverflow.com/a/47275518
This also explains why this might work with one JVM/OS combo and doesn't work with another JVM/OS combo.

Suggested solutions.
1. Re-write the test so that the file is not loaded from an `InputStream` but from a `File` instead. IMO, this is still a bit smelly.
2. Re-write so that we use our own custom resource resolver to resolve any schema resources by pointing to local files. This is a bit more work but the cleanest solution.
3. Change the XML so as to use a externally hosted XSD. Personally, I would always try to avoid relying on an internet connection and the availability of external resources if the functionality of my own code does not crucially depend on this. Otherwise your tests file but it has nothing to do with your own code and wouldn't even impact on the everyday functionality of your code, but makes your test fail.

**Comment by johnmay** [comment] 2022-08-29 08:28
The odd thing is you can see the automated build works without issue on multiple java versions. The resolver does some more optimal but I’m not satisfied as to why it works many other places but not on your machine/ide. I do also use IntelliJ but run the tests via maven so will check more once I’m back at work

**Comment by johnmay** [comment] 2022-08-29 11:13
In fact yes I think the issue is perhaps running via the ide you get the wrong relative path. Could you confirm running the tests from the IntelliJ maven side bar does/does not fail.

- John

**Comment by johnmay** [comment] 2022-08-29 13:58
If you run the test like this:

<img width="516" alt="Screenshot 2022-08-29 at 14 56 51" src="https://user-images.githubusercontent.com/983232/187218129-2c214b5a-3a49-4bce-baec-6571e8142896.png">

Does it pass? In which case it's an issue with your working directory when trying to run all the tests. A custom XSD resolution may still be helpful but not sure it's needed.

**Comment by johnmay** [comment] 2022-08-29 14:01
In fact I'm curious how you managed to get IntelliJ to run all the tests... if I do "Run All Tests" by right clicking on the root I get an error "No junit.jar" which is correct since the root is a POM and is only organisational.

**Comment by johnmay** [comment] 2022-08-29 14:06
OK, OK, poking around a little more I think the following is failing and due to your logging issues you are missing the warning. As a guess it could be your are on Windows and the paths need backslash instead of forward slash. 

```
try {
    InputStream in = AtomTypeFactoryTest.class.getClassLoader().getResourceAsStream(
            "org/openscience/cdk/io/cml/data/cml25b1.xsd");
    tmpCMLSchema = copyFileToTmp("cml2.5.b1", ".xsd", in, null, null);
} catch (IOException e) {
    LoggingToolFactory.createLoggingTool(AtomTypeFactoryTest.class)
                      .warn("Unexpected Error:", e);
}
```

**Comment by johnmay** [comment] 2022-08-29 14:08
More crazy is the assertValidCML which is called multiple times is copying the file multiple times. OK a resolver really would be much more correct here.

```java
    private void assertValidCML(String atomTypeList, String shortcut) throws Exception {
        InputStream ins = this.getClass().getClassLoader().getResourceAsStream(atomTypeList);
        File tmpInput = copyFileToTmp(shortcut, ".cmlinput", ins, "../../io/cml/data/cml25b1.xsd", "file://"
                + tmpCMLSchema.getAbsolutePath());
        Assert.assertNotNull("Could not find the atom type list CML source", ins);
```

**Comment by uli-f** [comment] 2022-08-30 01:55
> The odd thing is you can see the automated build works without issue on multiple java versions. The resolver does some more optimal but I’m not satisfied as to why it works many other places but not on your machine/ide. I do also use IntelliJ but run the tests via maven so will check more once I’m back at work

I get your point, but irrespective of the particular combo of JVM/OS the way this is implemented isn't guaranteed to work. _Might_ be more OS dependent than JVM dependent, so I guess it is a good thing that someone ran this on Windows 😁

**Comment by uli-f** [comment] 2022-08-30 02:46
> In fact yes I think the issue is perhaps running via the ide you get the wrong relative path. Could you confirm running the tests from the IntelliJ maven side bar does/does not fail.

I am on Intellij IDEA 2022.2.1 (Ultimate Edition). When creating a new project from source control in IntelliJ and pointing to `https://github.com/cdk/cdk.git`, the IDE checks out the sources and recognizes it as a multi module maven project. This sets everything up so that I can control maven goals using the IDE.

![intellij panel project](https://user-images.githubusercontent.com/98144814/187336743-9699dc88-6ef9-4826-86e3-11dc186fbf9e.png)

When I run all test from the maven panel

![intellij panel maven](https://user-images.githubusercontent.com/98144814/187337083-76fc73aa-e757-4263-9b35-25405d4ef934.png)

it fails for the ones mentioned here and in #881.

**Comment by uli-f** [comment] 2022-08-30 02:49
> If you run the test like this:
> 
> <img alt="Screenshot 2022-08-29 at 14 56 51" width="516" src="https://user-images.githubusercontent.com/983232/187218129-2c214b5a-3a49-4bce-baec-6571e8142896.png">
> 
> Does it pass? In which case it's an issue with your working directory when trying to run all the tests. A custom XSD resolution may still be helpful but not sure it's needed.

If running the tests like you suggested

![intellij run test class](https://user-images.githubusercontent.com/98144814/187337606-11dd1327-6f5e-4a08-b50b-e2db75ff4eca.png)

tests still fail for the five tests in `AtomTypeFactoryTest`.

**Comment by uli-f** [comment] 2022-08-30 02:51
The five tests in `AtomTypeFactoryTest` also fail if running the tests by executing `maven clean compile test` from a terminal:

![terminal test failures](https://user-images.githubusercontent.com/98144814/187337825-67c39b9f-c77f-4367-8f0a-180f89096f8e.png)

**Comment by uli-f** [comment] 2022-08-30 02:57
> In fact I'm curious how you managed to get IntelliJ to run all the tests... if I do "Run All Tests" by right clicking on the root I get an error "No junit.jar" which is correct since the root is a POM and is only organisational.

That doesn't work for me either.

But running the tests from the maven project panel by selecting the maven goal test works fine and runs the tests of all modules.

**Comment by uli-f** [comment] 2022-08-30 03:03
> OK, OK, poking around a little more I think the following is failing and due to your logging issues you are missing the warning. As a guess it could be your are on Windows and the paths need backslash instead of forward slash.
> 
> ```
> try {
>     InputStream in = AtomTypeFactoryTest.class.getClassLoader().getResourceAsStream(
>             "org/openscience/cdk/io/cml/data/cml25b1.xsd");
>     tmpCMLSchema = copyFileToTmp("cml2.5.b1", ".xsd", in, null, null);
> } catch (IOException e) {
>     LoggingToolFactory.createLoggingTool(AtomTypeFactoryTest.class)
>                       .warn("Unexpected Error:", e);
> }
> ```
> 
> (That is at the top of the AtomTypeFactoryTest) class.

This doesn't seem to be the problem here.

![debug](https://user-images.githubusercontent.com/98144814/187339288-f48a6c44-96d8-4f18-961b-20ac4a20bea2.png)


When setting a break point and running `AtomTypeFactoryTest` in debug mode it does not stop, so the catch clause isn't entered.

**Comment by uli-f** [comment] 2022-08-30 03:30
> Can you try #884. I removed all the file copy gubbins and use an entity resolver instead.

#884 fixes #881 for me.

`AtomTypeFactoryTest` works fine now 👍🏼 

However, `XMLIsotopeFactoryTest` needs the same attention.

Was just about to do that but I don't see the #881 branch in my fork https://github.com/uli-f/cdk/, so I cannot pick up the work on that... 😢

**Comment by johnmay** [comment] 2022-08-30 06:31
Thanks I’ll do the same for the isotope factory. As as I saw the file copies I was like hmm this code looks very funky. Other than the depiction one (also fixed in that patch) is that all the (active) tests passing?

**Comment by johnmay** [comment] 2022-08-30 06:32
Oh there is a way to branch of a PR, you need to add cdk/cdk as a new remote then fetch/check out my branch. When submitting the PR you merge it back to this PR

**Comment by uli-f** [comment] 2022-08-30 06:36
> Oh there is a way to branch of a PR, you need to add cdk/cdk as a new remote then fetch/check out my branch. When submitting the PR you merge it back to this PR

Okay, would like to try that workflow.

Are you happy for me to do the work on `XMLIsotopeFactoryTest` to test out the workflow on a real life example?

**Comment by johnmay** [comment] 2022-08-30 06:39
Sure

**Comment by uli-f** [comment] 2022-08-30 08:09
Wow, that is a pretty neat workflow! Thanks for pointing that out, wasn't aware.

I cleaned up a little bit in both test classes, hope you don't mind.

> Other than the depiction one (also fixed in that patch) is that all the (active) tests passing?

All tests work now on my PR 💯

**Closed** 2022-08-31 06:09 UTC
