### ISSUE TITLE
Calculation of PartialSigmaChargeDescriptor affects the result of EffectiveAtomPolarizabilityDescriptor

### ISSUE THREAD

**Issue by martin-sicho** [cdk/cdk#517] opened 2018-12-13 13:59 UTC
I have the following code in CDK 2.2, which calculates `EffectiveAtomPolarizabilityDescriptor` and `PartialSigmaChargeDescriptor` as follows:

```java
package main;

import org.openscience.cdk.DefaultChemObjectBuilder;
import org.openscience.cdk.interfaces.IAtom;
import org.openscience.cdk.interfaces.IAtomContainer;
import org.openscience.cdk.qsar.IAtomicDescriptor;
import org.openscience.cdk.qsar.descriptors.atomic.*;
import org.openscience.cdk.smiles.SmilesParser;
import org.openscience.cdk.tools.manipulator.AtomContainerManipulator;

public class Main {

    public static void main(String[] args) throws Exception {
        SmilesParser sparser = new SmilesParser(DefaultChemObjectBuilder.getInstance());
        String smiles = "CN(C)C";
        IAtomContainer molecule = sparser.parseSmiles(smiles);
        
        // even this does not help the case
        AtomContainerManipulator.percieveAtomTypesAndConfigureUnsetProperties(molecule);

        IAtomicDescriptor eap_desc = new EffectiveAtomPolarizabilityDescriptor();
        IAtomicDescriptor psc_desc = new PartialSigmaChargeDescriptor();
        for(IAtom atom : molecule.atoms()) {
            if (atom.getSymbol().equals("C")) {
                System.out.println("Atom" + atom.toString());

                // changes value after PartialSigmaChargeDescriptor is calculated
                System.out.println("EffectiveAtomPolarizabilityDescriptor: " + eap_desc.calculate(atom, molecule).getValue().toString());

                // modifies structure
                System.out.println("PartialSigmaChargeDescriptor: " + psc_desc.calculate(atom, molecule).getValue().toString());
            }
        }
    }
}
```

Output:

```
AtomAtomRef{Atom(1020923989, S:C, H:3, AtomType(1020923989, N:C.sp3, MBO:SINGLE, BOS:4.0, FC:0, H:SP3, NC:4, EV:4, Isotope(1020923989, Element(1020923989, S:C, AN:6))))}
EffectiveAtomPolarizabilityDescriptor: 4.963500000000002
PartialSigmaChargeDescriptor: 0.08989854429298508
AtomAtomRef{Atom(1018937824, S:C, H:0, C:0.08989854429298508, AtomType(1018937824, N:C.sp3, MBO:SINGLE, BOS:4.0, FC:0, H:SP3, NC:4, EV:4, Isotope(1018937824, Element(1018937824, S:C, AN:6))))}
EffectiveAtomPolarizabilityDescriptor: 4.9595
PartialSigmaChargeDescriptor: 0.08989854429298508
AtomAtomRef{Atom(905654280, S:C, H:0, C:0.08989854429298508, AtomType(905654280, N:C.sp3, MBO:SINGLE, BOS:4.0, FC:0, H:SP3, NC:4, EV:4, Isotope(905654280, Element(905654280, S:C, AN:6))))}
EffectiveAtomPolarizabilityDescriptor: 4.959500000000002
PartialSigmaChargeDescriptor: 0.08989854429298508

Process finished with exit code 0
```

Apparently, the result of this calculation depends on the order of atoms in the molecule since the `PartialSigmaChargeDescriptor` modifies the original structure somehow and as a result `EffectiveAtomPolarizabilityDescriptor` then differs slightly for the remaining carbon atoms, which should in principle be equivalent. 

Thus, I have two questions:

1. Is it intended behavior that an atom descriptor calculation can affect the inner representation of the input molecule? Is this how the `PartialSigmaChargeDescriptor` class should behave?
2. How should I prepare the structure to ensure that the descriptor values are correct and consistent and do not depend on the order of descriptor calculations?

Thanks a lot for any ideas on this!

**Comment by johnmay** [comment] 2018-12-13 16:59
It is not intended behaviour but I know about and don't even think we can fix it. I thought I deprecated this actually but might be another incarnation. IIRC there are some magic numbers from an old machine learning model which we can't adjust because we don't have the model.

> How should I prepare the structure to ensure that the descriptor values are correct and consistent and do not depend on the order of descriptor calculations?

I think simply can't use the descriptor....

**Comment by martin-sicho** [comment] 2018-12-14 12:11
Oh that is very unfortunate, but I guess nothing can be done in this case. But do you think it would make sense for me to first calculate `PartialSigmaChargeDescriptor` and then `EffectiveAtomPolarizabilityDescriptor` to ensure same results are obtained for all atoms at least? Or vice versa? Or running the calculations on separate copies of the molecule? I am guessing that if the `PartialSigmaChargeDescriptor` is not giving numbers that are plain wrong, it could still somehow be usable when we control for the possible interference with other descriptors...

Nevertheless, thanks again for the answer. Maybe it would be worthwhile to really deprecate this offending descriptor in the next release so there is a compile time warning linking to this issue or something like that...

**Comment by johnmay** [comment] 2018-12-14 13:00
I will have a look this weekend and get back to you

**Comment by johnmay** [comment] 2018-12-14 13:03
I've realised the magic numbers I was referring to were in a different piece of code: https://github.com/cdk/cdk/blob/master/legacy/src/main/java/org/openscience/cdk/tools/IonizationPotentialTool.java#L365-L451 so it might well fixable but don't have time today to look at it. I will try this weekend but if not over Xmas break I'll work out the way forward.

**Comment by martin-sicho** [comment] 2018-12-14 13:18
That's great news! Thank you so much! 

I am training some machine learning models for which these descriptors prove to be quite influential and while the models are somewhat robust to slight value changes like this, it can still throw them off by some margin so I would really like to remove any potential noise this could cause. Would be a great help if you could find a solution to this. 

I will try to dig into it as well, but I probably lack the knowledge to be of much help here. By the time I understand what exactly the code does, you probably will have finished the fix.

**Comment by johnmay** [comment] 2018-12-20 19:11
Should be fixed, sorry I miss-understood your issue we have has cases where the storage order in the molecule (e.g. CC=O vs O=CC) changes the descriptor value. Actually in this case it was the ordering of descriptors should absolutely be independant and should always be resolvable.

In this case only one atom was being saved/rolled back when we need all atoms to do that. Patch here: #521.

**Closed by johnmay** 2018-12-20 19:11 UTC

**Comment by martin-sicho** [comment] 2018-12-22 14:49
Great! Thanks a lot for the fix. I'm really glad it was this easy in the end.
