### ISSUE TITLE
local regression for formula

### ISSUE THREAD

**Issue by egonw** [cdk/cdk#452] opened 2018-05-18 09:29 UTC
I get this local error with the latest version when running the tests locally with "mvn test":

```
[INFO] Running org.openscience.cdk.tools.manipulator.MolecularFormulaManipulatorTest
[ERROR] Tests run: 85, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.421 s <<< FAILURE! - in org.openscience.cdk.tools.manipulator.MolecularFormulaManipulatorTest
[ERROR] testMassNumberDisplay(org.openscience.cdk.tools.manipulator.MolecularFormulaManipulatorTest)  Time elapsed: 0.007 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is "C7H3[81Br]BrO3"
     but: was "C7H3Br[81Br]O3"
        at org.openscience.cdk.tools.manipulator.MolecularFormulaManipulatorTest.testMassNumberDisplay(MolecularFormulaManipulatorTest.java:1339)
```

**Comment by johnmay** [comment] 2018-05-18 09:54
Hmm...

```
harbinger:formula john$ mvn test -o
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.openscience.cdk:cdk-formula >-------------------
[INFO] Building cdk-formula 2.2-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ cdk-formula ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/john/GitHub/cdk/tool/formula/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ cdk-formula ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ cdk-formula ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/john/GitHub/cdk/tool/formula/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ cdk-formula ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.20:test (default-test) @ cdk-formula ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Using the new AtomContainer implementation.
[INFO] Running org.openscience.cdk.tools.manipulator.MolecularFormulaManipulatorTest
[INFO] Tests run: 85, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.343 s - in org.openscience.cdk.tools.manipulator.MolecularFormulaManipulatorTest
[INFO] Running org.openscience.cdk.tools.manipulator.MolecularFormulaSetManipulatorTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.openscience.cdk.tools.manipulator.MolecularFormulaSetManipulatorTest
[INFO] Running org.openscience.cdk.tools.manipulator.MolecularFormulaRangeManipulatorTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.openscience.cdk.tools.manipulator.MolecularFormulaRangeManipulatorTest
[INFO] Running org.openscience.cdk.formula.IsotopePatternTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.openscience.cdk.formula.IsotopePatternTest
[INFO] Running org.openscience.cdk.formula.MolecularFormulaGeneratorTest
[INFO] Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.156 s - in org.openscience.cdk.formula.MolecularFormulaGeneratorTest
[INFO] Running org.openscience.cdk.formula.IsotopeContainerTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in org.openscience.cdk.formula.IsotopeContainerTest
[INFO] Running org.openscience.cdk.formula.IsotopePatternGeneratorTest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.929 s - in org.openscience.cdk.formula.IsotopePatternGeneratorTest
[INFO] Running org.openscience.cdk.formula.MolecularFormulaRangeTest
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.openscience.cdk.formula.MolecularFormulaRangeTest
[INFO] Running org.openscience.cdk.formula.rules.ToleranceRangeRuleTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.openscience.cdk.formula.rules.ToleranceRangeRuleTest
[INFO] Running org.openscience.cdk.formula.rules.ChargeRuleTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.openscience.cdk.formula.rules.ChargeRuleTest
[INFO] Running org.openscience.cdk.formula.rules.IsotopePatternRuleTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in org.openscience.cdk.formula.rules.IsotopePatternRuleTest
[INFO] Running org.openscience.cdk.formula.rules.NitrogenRuleTest
[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.openscience.cdk.formula.rules.NitrogenRuleTest
[INFO] Running org.openscience.cdk.formula.rules.ElementRuleTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in org.openscience.cdk.formula.rules.ElementRuleTest
[INFO] Running org.openscience.cdk.formula.rules.RDBERuleTest
[INFO] Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 s - in org.openscience.cdk.formula.rules.RDBERuleTest
[INFO] Running org.openscience.cdk.formula.rules.MMElementRuleTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.openscience.cdk.formula.rules.MMElementRuleTest
[INFO] Running org.openscience.cdk.formula.IsotopePatternManipulatorTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.openscience.cdk.formula.IsotopePatternManipulatorTest
[INFO] Running org.openscience.cdk.formula.IsotopePatternSimilarityTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.035 s - in org.openscience.cdk.formula.IsotopePatternSimilarityTest
[INFO] Running org.openscience.cdk.formula.MolecularFormulaCheckerTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in org.openscience.cdk.formula.MolecularFormulaCheckerTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 293, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.131 s
[INFO] Finished at: 2018-05-18T10:54:15+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by johnmay** [comment] 2018-05-18 09:57
Can't check travis, since we made the logging work correctly where is just a spam of suppress those CML/PDB warnings and is too long to see if the build actually passed or not.

**Comment by egonw** [comment] 2018-05-18 09:57
I will further explore this, but looking into an issue with V2000 exporting first (NPE...)

**Comment by egonw** [comment] 2018-05-18 11:30
OK, about what I was working on: that NPE in V2000 export turns out to be a SGRP clone() issue and fixed in this January patch and Tim (Squonk) is verifying 2.2-SNAPSHOT fixes the issue... any release to Maven Central on the horizon?

**Comment by johnmay** [comment] 2018-05-18 11:56
Possible but I'm not clear where you're having a problem at the moment...?

**Comment by egonw** [comment] 2018-05-18 12:28
The problems is a NPE during exporting of MDLV2000... it very much looks to be the SGRP not being cloned to be the issue, which you fixed in January... so, after the 2.1.1 release... because the groups are not cloned, upon export it accesses the group info, to find the atom indices to not work, causing the NPE...

**Comment by egonw** [comment] 2018-05-18 12:28
(just for clarity, that's not about the regression!)

**Comment by johnmay** [comment] 2018-05-18 19:17
I get a single regression in NonPlanarBondsTest where I've forgot to check in the BEAM changes (will do next - as on other computer). I do see the usual problems with CML on Java 10, "don't know how to validate for Java x.x". Really should just remove that check there are more portable ways to do this now.

**Comment by egonw** [comment] 2018-06-15 19:02
Mmm... that recent patch did not really improve it:

```
[ERROR] Failures: 
[ERROR]   ElementRuleTest>FormulaRuleTest.testGetParameters:78 A parameter default must not be null.
[ERROR]   IsotopePatternRuleTest>FormulaRuleTest.testGetParameters:78 A parameter default must not be null.
[ERROR]   MolecularFormulaManipulatorTest.testMassNumberDisplay:1339 
Expected: is "C7H3[81]BrBrO3"
     but: was "C7H3Br[81]BrO3"
[ERROR]   MolecularFormulaManipulatorTest.testMassNumberDisplayWithDefinedIsotopes:1356 
Expected: is "C7H3Br[81]BrO3"
     but: was "C7H3[81]BrBrO3"
[ERROR] Errors: 
[ERROR]   IsotopePatternRuleTest>FormulaRuleTest.testSetParameters_arrayObject:86 » CDK ...
[ERROR]   IsotopePatternRuleTest>FormulaRuleTest.testValidate_IMolecularFormula:96 » NullPointer
```

**Comment by johnmay** [comment] 2018-06-16 11:51
Okay will look into it today, also seeing lots of failures in SMSD. that's from when I switched the operands to remove a warning.. I think maybe time to just deleted it (already in the legacy module).

**Comment by johnmay** [comment] 2018-06-18 08:13
Okay found the problem, the MF data structure uses a map so the order can flip around randomly, hence didn't see when I committed it. Simple to fix with a sort when generating the MF. Just seeing if I can fix the SMSD problems too.

**Closed** 2018-06-21 18:50 UTC
