### ISSUE TITLE
raising NullPointerException when generating fragments from phosphor-included molecules

### ISSUE THREAD

**Issue by biotech7** [cdk/cdk#761] opened 2021-10-29 14:11 UTC
By utilizing of ExhaustiveFragmenter() to generate fragments. In some cases(including phosphor) it raises NullPointerException, e.g:

```java
String smiles = "FC(O)C(=O)C(=C)/C=N\\C(=N)CC(SC(C)P(=O)(O)O)C\\C=C\\CC2CCCc1cc3CCCc3cc12";
IChemObjectBuilder bldr = SilentChemObjectBuilder.getInstance();
SmilesParser smipar = new SmilesParser(bldr);
IAtomContainer mol = smipar.parseSmiles(smiles);
IFragmenter gf = new ExhaustiveFragmenter();
gf.generateFragments(mol);//----raising NullPointerException
```

error as follow:

```
Exception in thread "main" java.lang.NullPointerException
 	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.perceivePhosphors(CDKAtomTypeMatcher.java:1373)
 	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.findMatchingAtomType(CDKAtomTypeMatcher.java:141)
 	at org.openscience.cdk.atomtype.CDKAtomTypeMatcher.findMatchingAtomType(CDKAtomTypeMatcher.java:122)
 	at org.openscience.cdk.tools.manipulator.AtomContainerManipulator.percieveAtomTypesAndConfigureAtoms(AtomContainerManipulator.java:1514)
 	at org.openscience.cdk.fragment.ExhaustiveFragmenter.run(ExhaustiveFragmenter.java:121)
 	at org.openscience.cdk.fragment.ExhaustiveFragmenter.generateFragments(ExhaustiveFragmenter.java:101)
```

**Comment by egonw** [comment] 2021-10-30 19:32
Which version of the CDK are you using? I cannot reproduce the problem yet.

**Comment by biotech7** [comment] 2021-10-31 05:05
CDK version 2.5. 
IDE env. IDEA /JDK 1.8 /Win 10.

**Comment by johnmay** [comment] 2021-11-02 09:58
It's fixed in the SNAPSHOT 2.6-SNAPSHOT there was an issue with the atom-typer a few months ago:

```
O=C(C(=C)C=NC(=N)CCSC(C)P(=O)(O)O)C(F)O
O=CC(=C)C=NC(=N)CCSC(C)P(=O)(O)O
N=C(N=CC=C)CC(S)CC=CC
O=C(C(=C)C=NC(=N)CCC)C(F)O
S(CC)C(C)CC=CC
N=CCCSCC
O=P(O)(O)C(SC)C
S(CC)C(C)CC=CCC1c2cc3c(cc2CCC1)CCC3
N=C(N)CCCC=CC
N=C(N)CC(SCC)C
N=C(N=CC=C)CC(S)CC
O=P(O)(O)C(SCCC=N)C
N=C(N=CC=C)CC(SCC)CC=CCC1c2cc3c(cc2CCC1)CCC3
S(CC)C(C)C
O=P(O)(O)C(SCCC)C
O=P(O)(O)C(SC(C)CC(=N)N)C
O=C(C(=C)C=NC(=N)CC(SCC)CC)C(F)O
N=C(N)CC(S)CC=C
O=P(O)(O)C(SC(CC=C)CC(=N)N)C
N=C(N=C)CC(SCC)CC=CC
O=CC(=C)C=NC(=N)CC(SC(C)P(=O)(O)O)CC=C
N=C(N)CCSCC
N=C(N=CC=C)CC(S)CC=CCC1c2cc3c(cc2CCC1)CCC3
O=C(C(=C)C=NC(=N)CC(SCC)C)C(F)O
N=C(N=CC=C)CCSCC
O=CC(=C)C=NC(=N)CCCC
N=C(N)CCCC
N=C(N=C)CCCC
N=C(N=C)CC(S)CC=CCC1c2cc3c(cc2CCC1)CCC3
O=CC(=C)C=NC(=N)CC(S)CC
N=C(N)CC(SCC)CC=CCC1c2cc3c(cc2CCC1)CCC3
O=P(O)(O)C(SC(CC=N)CC=CCC1c2cc3c(cc2CCC1)CCC3)C
N=C(N=C)CC(SCC)C
N=CCC(SCC)C
N=CCC(SCC)CC=CC
O=P(O)(O)C(SC(CC=N)CC=C)C
O=C(C(=C)C=NC(=N)CC(SC(C)P(=O)(O)O)CC=CC)C(F)O
O=P(O)(O)C(SC(C)CC)C
c1c2c(cc3c1CCCC3)CCC2
O=P(O)(O)C(SC(CC(=N)N=C)CC)C
O=P(O)(O)C(SC(CC=C)CC(=N)N=C)C
N=C(N=C)CC(S)C
O=P(O)(O)C(SC(C)CC=N)C
C(=CCC1c2cc3c(cc2CCC1)CCC3)CC
N=CCCCC
N=C(N)CC(SCC)CC
O=P(O)(O)C(SC(C)CC=CCC1c2cc3c(cc2CCC1)CCC3)C
N=CCCCC=C
N=C(N)CC(S)CC=CCC1c2cc3c(cc2CCC1)CCC3
N=C(N)CC(S)CC
N=C(N=C)CC(SCC)CC=C
N=C(N=CC=C)C
N=C(N)CC(SCC)CC=CC
O=P(O)(O)C(SC(CC=N)CC)C
O=CC(=C)C=NC(=N)CCCC=C
O=CC(=C)C=NC(=N)CC(SCC)C
O=P(O)(O)C(SC(CC=CC)CC(=N)N=C)C
N=C(N=C)CC(SCC)CC
O=P(O)(O)C(SCCC=CCC1c2cc3c(cc2CCC1)CCC3)C
N=CCC(SCC)CC
O=CC(=C)C=NC(=N)CC(SC(C)P(=O)(O)O)CC=CCC1c2cc3c(cc2CCC1)CCC3
O=C(C(=C)C=NC(=N)CC(SC(C)P(=O)(O)O)CC)C(F)O
c1c2c(cc3c1CCCC3CC)CCC2
O=P(O)(O)C(S)C
N=C(N=C)CCCC=CC
O=C(C(=C)C=N)C(F)O
N=C(N=CC=C)CC(S)CC=C
N=C(N=C)CC(SCC)CC=CCC1c2cc3c(cc2CCC1)CCC3
O=CC(=C)C=NC(=N)CC(S)CC=C
O=C(C(=C)C=NC(=N)CC)C(F)O
O=P(O)(O)CC
O=P(O)(O)C(SCCC(=N)N=CC=C)C
c1c2c(cc3c1CCCC3C)CCC2
SCCC=CC
O=P(O)(O)C(SC(CC=CC)CC(=N)N=CC=C)C
O=C(C(=C)C=NC(=N)CC(S)CC)C(F)O
O=C(C(=C)C=NC(=N)CCCC=CCC1c2cc3c(cc2CCC1)CCC3)C(F)O
O=C(C(=C)C=NC(=N)CC(SCC)CC=CCC1c2cc3c(cc2CCC1)CCC3)C(F)O
N=CCCCC=CCC1c2cc3c(cc2CCC1)CCC3
N=C(N=CC=C)CC
N=CCC(S)CC
C(=CCC1c2cc3c(cc2CCC1)CCC3)C
N=C(N=CC=C)CCCC=C
O=C(C(=C)C=NC(=N)CC(S)CC=C)C(F)O
O=P(O)(O)C(SCCC(=N)N=C)C
O=C(C(=C)C=NC(=N)CC(S)C)C(F)O
SC(C)CC=CC
O=CC(=C)C=NC(=N)CC(SCC)CC=CCC1c2cc3c(cc2CCC1)CCC3
O=C(C(=C)C=NC(=N)CC(S)CC=CCC1c2cc3c(cc2CCC1)CCC3)C(F)O
O=CC(=C)C=N
N=C(N)CC(S)CC=CC
S(CC)CCC=CC
N=CCC(SCC)CC=C
N=C(N)CC(SCC)CC=C
O=P(O)(O)C(SC(CC=C)CC(=N)N=CC=C)C
O=P(O)(O)C(SC(C)CC=CC)C
N=C(N=C)CC(S)CC
O=P(O)(O)C(SC(C)CC(=N)N=C)C
N=C(N=CC=C)CC(SCC)CC=C
O=P(O)(O)C(SC(C)CC=C)C
O=CC(=C)C=NC(=N)CC(SC(C)P(=O)(O)O)C
N=C(N)CC(S)C
C(=CCCC)C
O=P(O)(O)C(SC(CC=CCC1c2cc3c(cc2CCC1)CCC3)CC(=N)N)C
O=C(C(=C)C=NC(=N)CC(SCC)CC=C)C(F)O
O=P(O)(O)C(SC(CC=CCC1c2cc3c(cc2CCC1)CCC3)CC(=N)N=C)C
O=CC(=C)C=NC(=N)CCCC=CCC1c2cc3c(cc2CCC1)CCC3
N=CCC(S)CC=CCC1c2cc3c(cc2CCC1)CCC3
O=CC(=C)C=NC(=N)CC
O=CC(=C)C=NC(=N)C
O=CC(=C)C=NC(=N)CC(S)C
O=P(O)(O)C(SCCC(=N)N)C
O=P(O)(O)C(SC(CC=CC)CC(=N)N)C
N=C(N=C)CCC
S(CC)C(C)CC
S(CC)C(C)CC=C
O=P(O)(O)C(SCCC=CC)C
N=C(N=C)CC
N=CCC(S)C
S(CC)CCC=C
O=C(C(=C)C=NC(=N)C)C(F)O
O=C(C(=C)C=NC(=N)CC(SC(C)P(=O)(O)O)C)C(F)O
N=C(N)CCS
N=C(N=C)CCCC=C
N=CCCCC=CC
O=CC(=C)C=NC(=N)CC(SC(C)P(=O)(O)O)CC=CC
O=CC(=C)C=NC(=N)CCCC=CC
N=C(N=C)CCS
O=P(O)(O)C(SC(CC(=N)N=CC=C)CC)C
O=P(O)(O)C(SC(C)C)C
O=C(C(=C)C=NC(=N)CCSCC)C(F)O
N=C(N=CC=C)CC(SCC)CC
N=CCC(S)CC=C
O=CC(=C)C=NC(=N)CC(SCC)CC
N=C(N=CC=C)CC(SCC)C
C=CCC1c2cc3c(cc2CCC1)CCC3
C(=CCC1c2cc3c(cc2CCC1)CCC3)CCC
N=C(N=CC=C)CCC
O=C(C(=C)C=NC(=N)CCCC=CC)C(F)O
N=C(N=CC=C)CC(S)C
O=P(O)(O)C(SC(C)CC(=N)N=CC=C)C
SCCC=CCC1c2cc3c(cc2CCC1)CCC3
N=C(N=C)CCCC=CCC1c2cc3c(cc2CCC1)CCC3
O=CC(=C)C=NC(=N)CCS
O=C(C(=C)C=NC(=N)CC(S)CC=CC)C(F)O
N=C(N)CCCC=CCC1c2cc3c(cc2CCC1)CCC3
O=C(C(=C)C=NC=N)C(F)O
SC(C)CC=CCC1c2cc3c(cc2CCC1)CCC3
O=P(O)(O)C(SC(CC=CCC1c2cc3c(cc2CCC1)CCC3)CC(=N)N=CC=C)C
O=C(C(=C)C=NC(=N)CC(SC(C)P(=O)(O)O)CC=C)C(F)O
O=CC(=C)C=NC(=N)CC(S)CC=CC
S(CC)CCC=CCC1c2cc3c(cc2CCC1)CCC3
O=C(C(=C)C=NC(=N)CCCC)C(F)O
N=C(N=CC=C)CCS
N=C(N=C)CCSCC
N=C(N=CC=C)CCCC=CCC1c2cc3c(cc2CCC1)CCC3
N=C(N)CCC
N=C(N=CC=C)CCCC=CC
N=C(N=CC=C)CC(SCC)CC=CC
O=CC(=C)C=NC(=N)CC(SC(C)P(=O)(O)O)CC
O=C(C(=C)C=NC(=N)CCCC=C)C(F)O
N=C(N)CCCC=C
O=C(C(=C)C=NC(=N)CCS)C(F)O
O=CC(=C)C=NC(=N)CCSCC
N=C(N=C)CC(S)CC=CC
O=C(C(=C)C=NC(=N)CC(SCC)CC=CC)C(F)O
O=CC(=C)C=NC=N
N=CCC(S)CC=CC
O=P(O)(O)C(SCC)C
N=CCC(SCC)CC=CCC1c2cc3c(cc2CCC1)CCC3
O=C(C(=C)C)C(F)O
SC(C)CC=C
O=CC(=C)C=NC(=N)CC(SCC)CC=C
O=C(C=C)C(F)O
N=CN=CC=C
N=C(N=C)CC(S)CC=C
O=CC(=C)C=NC(=N)CCC
N=C(N=CC=C)CCCC
O=CC(=C)C=NC(=N)CC(SCC)CC=CC
O=P(O)(O)C(SC(CC=N)CC=CC)C
O=P(O)(O)C(SC(CC(=N)N)CC)C
O=P(O)(O)C(SCCC=C)C
O=CC(=C)C=NC(=N)CC(S)CC=CCC1c2cc3c(cc2CCC1)CCC3
S(CC)CCC
```

**Closed by johnmay** 2021-11-02 09:58 UTC

**Comment by egonw** [comment] 2021-11-02 10:23
@johnmay, the latest `-SNAPSHOT` on Maven Central has this fix?

**Comment by johnmay** [comment] 2021-11-02 11:04
I'll deploy it now to make sure
