### ISSUE TITLE
MurckoFragmenter - improve algorithm

### ISSUE THREAD

**Issue by zod1ac** [cdk/cdk#263] opened 2017-01-11 13:41 UTC
It seems that murckoFragmenter do a lot of stuff while fragmenting molecules so the runtime is very high. 
Example compound where I quit the fragmenter after 17 hours of fragmentation is: 
CHEMBL529226

Update:
Created a Testset with ~67000 Molecules from Chembl_22.1 with AtomCount from 50 to 150 Atoms.
CDK-Fragmenter needs ~3 hours to create the Fragments
PypelinePilot Fragmenter needs ~15 Minutes
DataWarrior Fragmenter needs ~3 Minutes

Some additional Information:
I analysed the run with VisualVM and saw that few Threads took a long time to process a Molecule. 
I created a ThreadDump and it seems that the function AtomContainer.getConnectedAtomLists() is in every Thread who stuck the last call of a Method.

Would be nice if there will be an improvement of the fragmenter.

**Comment by johnmay** [comment] 2017-08-22 18:04
Just getting round to sorting this out, IIRC do you just want the Murcko scaffold? The issue is the murcko frameworks (combinatorially large) is being computed. 

Just looking through DataWarrior where in the UI is i't Fragmenter... wanted to test CHEMBL529226

Thanks

**Comment by johnmay** [comment] 2018-06-27 17:31
Resolved by #466

**Closed by johnmay** 2018-06-27 17:31 UTC
